### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#31]
- [x] Move to production-sized instance
- [x] Remove no index, no follow, meta tags for search engines
- [x] DNS change
- [x] Set up SSL on new site
- [x] Purchase reserved instance 
- [x] Make a copy of the old jaz.com site somewhere in case we need to get to the information on it
- [x] Ditto the old projects.jaz.com data
- [x] Discontinue the Linode server

**Comment by cguardia** [comment]
@alecpm have we settled on an instance type for the production launch? If not, anything you recommend?

**Comment by alecpm** [comment]
I'd like to try it with a t2.medium.  The accumulating CPU credits should give good performance on those brief occasions where it's needed.

**Comment by cguardia** [comment]
@skleinfeldt when should I do the launch?

**Comment by skleinfeldt** [comment]
@cguardia sometime tonight - I will comment to you here when I'm ready. Still have a little content editing and some aliases to make. We also still have the outstanding issue with the the thumb crops, #91. And their is your ticket #94.

**Comment by cguardia** [comment]
#94 is done. Is #91 fixed yet? We are running on a t2.medium. Is the site responding well enough? 

Ready to switch when you tell me.

**Comment by skleinfeldt** [comment]
#91 is not fixed, I am about to save all the crops again, per my email. I'll let you know when I'm done.

The only other thing needed are these 2 trivial (hopefully) CSS tweaks, #64 and #106. @alecpm let us know when those are done. Or just coordinate with Carlos on IRC.

(PS My talk is on Thursday in case you didn't guess.)

**Comment by skleinfeldt** [comment]
I'm done! go ahead with launch as soon as @alecpm is ready!

On the performance - it seems okay. Not super snappy, but acceptable. I wonder whether all these image crop caching problems we're having is affecting it. Cover pages (which now mostly have images) are definitely not snappy.

**Comment by cguardia** [comment]
Made DNS switch! Now just a matter of waiting for it to propagate.

**Comment by skleinfeldt** [comment]
@cguardia a reminder to set up SSL for jaz.com

**Comment by skleinfeldt** [comment]
@cguardia although the SSL bullet is checked off on this ticket, I do not see SSL on the site, including the login page. I believe the intention was to wrap the whole site in SSL?

**Comment by skleinfeldt** [comment]
@cguardia still need you to set up SSL wrapping for the site.

**Comment by cguardia** [comment]
Finally did that last task. You can close this after you confirm.

**Comment by skleinfeldt** [comment]
Yay!
